
## Core Java {-}

### Module 01: jShell {-}

#### Display Output {-}

1. **Theory**:    `r text_spec("TODO", color = "red", bold = TRUE)`         
Overview of Java.  

1. **Example**:    `r text_spec("TODO", color = "red", bold = TRUE)`        
How to print output in java.     

1. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Write a Program to display "My first java program" in jShell file.    

1. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Write a Program to display "I am loving coding" in jShell file.     

1. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Write a Program to display "I am loving coding" in jShell file in 3 times in 3 lines.     

1. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Write a Program in jShell file which displays multiple line as follows: "I am loving coding" and "Programming is amazing".     

1. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Write a Program in jShell file which displays value 10.     

1. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Write a Program in jShell file which displays value 37.4.     

1. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Write a Program in jShell file which displays multiple lines as follows: "I am loving coding" and integer value 10.    

#### Variables, Data types {-}

10. **Theory**:    `r text_spec("TODO", color = "red", bold = TRUE)`         
Variable introduction.     

10. **Example**:    `r text_spec("TODO", color = "red", bold = TRUE)`        
How to create variable of type String and display its value..    

10. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Write a Program in jShell file which declares String type variable with value "Hollywood" and display its value.     

10. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Write a Program in jShell file which declares 2 String type variables with value "John" and "Marry" and display their values.    

10. **Example**:    `r text_spec("TODO", color = "red", bold = TRUE)`        
How to create variable of type int and display its value.    

10. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Write a Program in jShell file which declares int type variable with value 10 and display its value.     

10. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Write a Program in jShell file which declares 2 int type variables with value 10 and 20 and display their values.   

10. **Example**:    `r text_spec("TODO", color = "red", bold = TRUE)`        
How to create variable of type float and display its value.    

10. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Write a Program in jShell file which declares float type variable with value 37.4 and display its value.    

10. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Write a Program in jShell file which declares 2 float type variables with value 37.4 and 98.6 and display their values.   

10. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Write a Program in jShell file which declares 3 variables of types String, int and float respectively with values "John", 10 and 7.8 respectively and display their values.    

10. **Theory**:    `r text_spec("TODO", color = "red", bold = TRUE)`         
What is String concatenation.   

10. **Example**:    `r text_spec("TODO", color = "red", bold = TRUE)`        
How to do String concatenation.   

10. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Write a Program in jShell file which concatenates 2 String literlas in print statement.   

10. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Write a Program in jShell file which concatenates 3 String literlas in print statement.   

10. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Write a Program in jShell file which declares 2 String variables with some values and concatenates these variables in print statement.    

10. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Write a Program in jShell file which declares 3 String variables with some values and concatenates these variables in print statement.    

10. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Write a Program in jShell file which concatenates 1 String literla and 1 int literal in print statement.    

10. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Write a Program in jShell file which declares 2 variables of types String and int with some values and concatenates these variables in print statement.   

10. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Addition: Write a Program in jShell file which declares 3 int variables such as a=10, b=20, c=a+b. Print value variable c.    

10. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Subtraction: Write a Program in jShell file which declares 3 int variables such as a=100, b=40, c=a-b. Print value variable c.   

10. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Multiplication: Write a Program in jShell file which declares 3 int variables such as a=10, b=20, c=a*b. Print value variable c.    

10. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Division: Write a Program in jShell file which declares 3 int variables such as a=20, b=10, c=a/b. Print value variable c.    

10. **Theory**:    `r text_spec("TODO", color = "red", bold = TRUE)`         
Importance of comments.   

10. **Example**:    `r text_spec("TODO", color = "red", bold = TRUE)`        
How to comment and uncomment.   

10. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Comment few lines in given program such that it gives output 20.    

10. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Uncomment few lines in given program such that it gives output 30.    

10. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Comment/Uncomment few lines in given program such that it gives output "I love my country and I am proud of it."    

10. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Comment/Uncomment few lines in given program such that it gives output "Water boils at 100 degree Celsius temperature."    

### Module 02: Class, Main Method, Static Method, Static Block, Static Data Member {-}

#### Classes {-}

1. **Theory**:    `r text_spec("TODO", color = "red", bold = TRUE)`         
Switch to .java fie.    

1. **Example**:    `r text_spec("TODO", color = "red", bold = TRUE)`        
How to create empty class in java file.   

1. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Write a java program which contains an empty class file.    
Create class **MyFirsClass**.   

        class MyFirsClass {
        }

1. **Example**:    `r text_spec("TODO", color = "red", bold = TRUE)`        
How to create empty main method in java file.   
  
1. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Write a java program which contains an class file, in which an empty main method is created.    
Create class **MyClass**.   
Create empty **main** method.   

        class SampleClass {
          public static void main(String[] args) {
          }
        }

1. **Example**:    `r text_spec("TODO", color = "red", bold = TRUE)`        
How to print "Hello world" in main method in java file.   

1. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Print **I am loving coding**.    
Print **Programming is amazing**.  
Question:

        class SampleClass {
          public static void main(String[] args) {
            System.out.println("");
            System.out.println("");
          }
        }
Solution:

        class SampleClass {
          public static void main(String[] args) {
            System.out.println("I am loving coding");
            System.out.println("Programming is amazing");
          }
        }

1. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Print **10**.    
Question:

        class SampleClass {
          public static void main(String[] args) {
            System.out.println();
          }
        }
Solution:

        class SampleClass {
          public static void main(String[] args) {
            System.out.println(10);
          }
        }

1. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Print **37.4**.    
Question:

        class SampleClass {
          public static void main(String[] args) {
            System.out.println();
          }
        }
Solution:

        class SampleClass {
          public static void main(String[] args) {
            System.out.println(37.4);
          }
        }

1. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create variable **String** **name** = *"John"*.   
Create variable **int** **age** = *10*.   
Create variable **float** **grade** = *7.8*.   
Print value of **name**.   
Print value of **age**.   
Print value of **grade**.   
Question:

        class VariableCreation {
          public static void main(String[] args) {
            
            
            
            System.out.println();
            System.out.println();
            System.out.println();
          }
        }
Solution:

        class VariableCreation {
          public static void main(String[] args) {
            String name = "John";
            int age = 15;
            float grade = 7.8;
            System.out.println(name);
            System.out.println(age);
            System.out.println(grade);
          }
        }

1. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Addition:    
Create variable **int** **a** = *10*.   
Create variable **int** **b** = *20*.   
Create variable **int** **c** = **a** + **b**.      
Print value of **c**.    
Create variable **int** **p** = *11*.   
Create variable **int** **q** = *22*.   
Create variable **int** **r** = **p** + **q**.      
Print value of **r**.    
Create variable **int** **x** = *50*.   
Create variable **int** **y** = *150*.   
Create variable **int** **z** = **x** + **y**.      
Print value of **z**.  
Question:

        class VariableCreation {
          public static void main(String[] args) {
            
            
            
            System.out.println();
            
            
            
            
            System.out.println();
            
            
            
            
            System.out.println();
          }
        }
Solution:

        class VariableCreation {
          public static void main(String[] args) {
            int a = 10;
            int b = 20;
            int c = a + b;
            System.out.println(c);
            
            int p = 10;
            int q = 20;
            int r = p + q;
            System.out.println(r);
            
            int x = 10;
            int y = 20;
            int z = x + y;
            System.out.println(z);
          }
        }

#### Static Methods {-}

12. **Theory**:    `r text_spec("TODO", color = "red", bold = TRUE)`         
Importance of methods.    

12. **Example**:    `r text_spec("TODO", color = "red", bold = TRUE)`        
How to create method in java file.    

12. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Addition:   
Implement static method "addition(int number1, int number2)" which prints addition of given arguments.    
Question:

        class MyOperation {
          void addition(int number1, int number2){
            
          }

          public static void main(String[] args) {
            addition();
          }
        }
Solution:

        class MyOperation {
          void addition(int number1, int number2){
            int result = number1 + number2;
            System.out.println(result);
          }

          public static void main(String[] args) {
            addition();
          }
        }

12. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Subtraction:    
Implement static method "subtraction(int number1, int number2)" which prints subtraction of given arguments.   
Question:

        class MyOperation {
          void subtraction(int number1, int number2){
            
            
          }

          public static void main(String[] args) {
            subtraction();
          }
        }
Solution:

        class MyOperation {
          void subtraction(int number1, int number2){
            int result = number1 - number2;
            System.out.println(result);
          }

          public static void main(String[] args) {
            subtraction();
          }
        }

12. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Square:    
Implement static method "square(int number)" which prints square of given argument.   
Question:

        class MyOperations {
          void square(int number){
            
            
          }

          public static void main(String[] args) {
            square();
          }
        }
Solution:

        class MyOperations {
          void square(int number){
            int result = number * number;
            System.out.println(result);
          }

          public static void main(String[] args) {
            square();
          }
        }

12. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Cube:     
Implement static method "cube(int number)" which prints cube of given argument.    
Question:

        class MyOperations {
          void cube(int number){
            int result = number * number * number;
            System.out.println(result);
          }

          public static void main(String[] args) {
            cube();
          }
        }
Solution:

        class MyOperations {
          void cube(int number){
            
            
          }

          public static void main(String[] args) {
            cube();
          }
        }

12. **Example**:    `r text_spec("TODO", color = "red", bold = TRUE)`        
How to create method with return type.   

12. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create static method "echo(int number)" which returns the same number passed as argument.    
Question:

        class EchoMyNumber {
          
            
          

          public static void main(String[] args) {
            int returnedNumber = echo(10);
            System.out.println(returnedNumber);
          }
        }
Solution:

        class EchoMyNumber {
          int echo(int number){
            return number;
          }

          public static void main(String[] args) {
            int returnedNumber = echo(10);
            System.out.println(returnedNumber);
          }
        }

12. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create static method "echo(string message)" which returns the same message passed as argument.    
Question:

        class EchoMyMessage {
          
          
          

          public static void main(String[] args) {
            String returnedMessage = echo("I will come back");
            System.out.println(returnedMessage);
          }
        }
Solution:

        class EchoMyMessage {
          String echo(String message){
            return message;
          }

          public static void main(String[] args) {
            String returnedMessage = echo("I will come back");
            System.out.println(returnedMessage);
          }
        }

12. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Implement custom static method "main(string message)" which returns the same message passed as argument.  Question:  

        class Student {
          String main(String message){
            
          }

          public static void main(String[] args) {
            String returnedMessage = main("I will come back");
            System.out.println(returnedMessage);
          }
        }
Solution:  

        class Student {
          String main(String message){
            return message;
          }

          public static void main(String[] args) {
            String returnedMessage = main("I will come back");
            System.out.println(returnedMessage);
          }
        }      

12. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create instance method **printFullName()** which prints full name by calling **getFirstName()** and **getLastName()** methods and appending them such as final result is *John Marshal*.   
Question:

        class Student {
          String getFirstName(){
            return "John";
          }
          
          String getLastName(){
            return "Marshal";
          }
          
          void printFullName(){
            System.out.println(getFirstName() + " " + getLastName());
          }

          public static void main(String[] args) {
            printFullName();
          }
        }
Solution:

        class Student {
          String getFirstName(){
            return "John";
          }
          
          String getLastName(){
            return "Marshal";
          }
          
          void printFullName(){
            System.out.println();
          }

          public static void main(String[] args) {
            printFullName();
          }
        }

#### Static Block {-}

23. **Theory**:    `r text_spec("TODO", color = "red", bold = TRUE)`         
Importance of static block.    

23. **Example**:    `r text_spec("TODO", color = "red", bold = TRUE)`        
How to create static block in java file.

23. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create static block in java file which prints "In static block" message. Try execute this file.   
Question:

        class StaticBlocksImportance {
          
          
          
        }
Solution:

        class StaticBlocksImportance {
          static{
            System.out.println("In first static block");
          }
        }        

23. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create first static blocks which prints "In first static block" message.    
Create second static blocks which prints "In second static block" message. Try execute this java file.    
Question:

        class StaticBlocksImportance {
          static{
            System.out.println("");
          }
          
          static{
            System.out.println("");
          }
        }
Solution:

        class StaticBlocksImportance {
          static{
            System.out.println("In first static block");
          }
          
          static{
            System.out.println("In second static block");
          }
        }        

23. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
The first static block shall print "In first static block" message.    
The second static block shall print "In second static block" message.    
Create main method, which shall print "In main method". Try execute this java file.   
Question:

        class StaticBlocksImportance {
          static{
            System.out.println("");
          }
          
          
          
          
          
          public static void main(String[] args) {
            System.out.println("");
          }
        }
Solution:

        class StaticBlocksImportance {
          static{
            System.out.println("In first static block");
          }
          
          static{
            System.out.println("In second static block");
          }
          
          public static void main(String[] args) {
            System.out.println("In main method");
          }
        }        

23. **Theory**:    `r text_spec("TODO", color = "red", bold = TRUE)`         
Importance of order of static block.   

23. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
The first static block shall print "In first static block" message.    
Create main method, which shall print "In main method".   
The second static block shall print "In second static block" message.    
Try execute this java file.   
Question:

        class StaticBlocksImportance {
          static{
            System.out.println("In first static block");
          }
          
          public static void main(String[] args) {
            System.out.println("In main method");
          }
          
          static{
            System.out.println("In second static block");
          }
        }
Solution:

        class StaticBlocksImportance {
          static{
            System.out.println("");
          }
          
          public static void main(String[] args) {
            System.out.println("");
          }
          
          static{
            System.out.println("");
          }
        }        

#### Static Data Members {-}

30. **Theory**:    `r text_spec("TODO", color = "red", bold = TRUE)`         
Importance of static data members.    

30. **Example**:    `r text_spec("TODO", color = "red", bold = TRUE)`        
How to create static data member and its usage in java file.    

30. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create static data member **companyName** of type String.    
Assign value *Folks* to **companyName** in main method.  
Question:

        class Employee {
          
          
          public static void main(String[] args) {
            
            System.out.println(companyName);
          }
        }
Solution:

        class Employee {
          static String companyName;
          
          public static void main(String[] args) {
            companyName = "Folks";
            System.out.println(companyName);
          }
        }        

30. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Assign value *Folks* to **companyName** in main method.    
Implement **displayCompanyName** such that it prints value of **companyName**.   
Question:

        class Employee {
          static String companyName;
          
          static displayCompanyName{
            System.out.println();
          }

          public static void main(String[] args) {
            displayCompanyName();
          }
        }
Solution:

        class Employee {
          static String companyName = "Folks";
          
          static displayCompanyName{
            System.out.println(companyName);
          }

          public static void main(String[] args) {
            displayCompanyName();
          }
        }

30. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Implement **displayCompanyName** such that it prints value of **companyName**.   
Implement **displayCompanyNameDuplicate** such that it prints value of **companyName**.   
Question:

        class Employee {
          static String companyName = "Folks";
          
          static displayCompanyName{
            System.out.println();
          }
          
          static displayCompanyNameDuplicate{
            System.out.println();
          }

          public static void main(String[] args) {
            displayCompanyName();
            displayCompanyNameDuplicate();
          }
        }
Solution:

        class Employee {
          static String companyName = "Folks";
          
          static displayCompanyName{
            System.out.println(companyName);
          }
          
          static displayCompanyNameDuplicate{
            System.out.println(companyName);
          }

          public static void main(String[] args) {
            displayCompanyName();
            displayCompanyNameDuplicate();
          }
        }        

30. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Implement static method **doubleCompanyRating()** which doubles the value of **companyRating**.   
Implement static method **printCompanyRating()** which prints the value of **companyRating**.   
Question:

        class Employee {
          static int companyRating = 3;
          
          static void doubleCompanyRating(){
            
          }
          
          static void printCompanyRating(){
            System.out.println();
          }

          public static void main(String[] args) {
            doubleCompanyRating();
            printCompanyRating();
          }
        }
Solution:

        class Employee {
          static int companyRating = 3;
          
          static void doubleCompanyRating(){
            companyRating = companyRating * 2;
          }
          
          static void printCompanyRating(){
            System.out.println(companyRating);
          }

          public static void main(String[] args) {
            doubleCompanyRating();
            printCompanyRating();
          }
        }        

30. **Theory**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
How to refer static data member with class name.   

30. **Example**:    `r text_spec("TODO", color = "red", bold = TRUE)`        
How to refer static data member with class name.   

30. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Print value of **companyName** in main method by referring through class name.  
Question:

        class Employee {
          static String companyName;

          public static void main(String[] args) {
            companyName = "Folks";
            
          }
        }
Solution:

        class Employee {
          static String companyName;

          public static void main(String[] args) {
            companyName = "Folks";
            System.out.println(Employee.companyName);
          }
        }        

### Module 03: Control Flow Statements {-}

#### if else {-}

1. **Theory**:    `r text_spec("TODO", color = "red", bold = TRUE)`         
if else introduction   

1. **Example**:    `r text_spec("TODO", color = "red", bold = TRUE)`        
How to use if else.   

1. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Implement **isEligibleForVoting**. Add condition in **if** block such as value of **age** is greater than 18 then returns true.    
Question:

        public class Conditions {

          static boolean isEligibleForVoting(int age){
            
          }

          public static void main(String[] args) {
            int age = 25;
            boolean isEligible = isEligibleForVoting(age);
            System.out.println(isEligible);
          }
        }
Solution:

        public class Conditions {

          static boolean isEligibleForVoting(int age){
            if(age > 18){
              return true;
            }
            else{
              return false;
            }
          }

          public static void main(String[] args) {
            int age = 25;
            boolean isEligible = isEligibleForVoting(age);
            System.out.println(isEligible);
          }
        }
        
1. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Implement **calculateGreaterNumber**. Add condition in **if** block such as value of **number1** is greater than or equal to value of **number2** then returns **number1** otherwise return **number2**.    
Question:

        public class GreaterNumber {
          private static int calculateGreaterNumber(int number1, int number2) {
            
          }

          public static void main(String[] args) {
            int number1 = 10;
            int number2 = 20;

            int greaterNumber = calculateGreaterNumber(number1, number2);
            System.out.println("greater number is: " + greaterNumber);
          }
        }
Solution:

        public class GreaterNumber {
          private static int calculateGreaterNumber(int number1, int number2) {
            if(number1 >= number2) {
              return number1;
            }
            else {
              return number2;
            }
          }

          public static void main(String[] args) {
            int number1 = 10;
            int number2 = 20;

            int greaterNumber = calculateGreaterNumber(number1, number2);
            System.out.println("greater number is: " + greaterNumber);
          }
        }
        
1. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Implement **calculateSmallerNumber**. Add condition in **if** block such as value of **number1** is smaller than value of **number2** then returns **number1** otherwise return **number2**.    
Question:

        public class SmallerNumber {
          private static int calculateSmallerNumber(int number1, int number2) {
            
          }

          public static void main(String[] args) {
            int number1 = 10;
            int number2 = 20;

            int smallerNumber = calculateSmallerNumber(number1, number2);
            System.out.println("smaller number is: " + smallerNumber);
          }
        }
Solution:

        public class SmallerNumber {
          private static int calculateSmallerNumber(int number1, int number2) {
            if(number1 < number2) {
              return number1;
            }
            else {
              return number2;
            }
          }

          public static void main(String[] args) {
            int number1 = 10;
            int number2 = 20;

            int smallerNumber = calculateSmallerNumber(number1, number2);
            System.out.println("smaller number is: " + smallerNumber);
          }
        }

1. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Implement **calculateSmallerNumber**. Print **number1** and *number2* in same line. Add condition in **if** block such that if value of **number1** is smaller than value of **number2** then returns **number1** otherwise return **number2**.    
Question:

        public class SmallerNumber {
          private static int calculateSmallerNumber(int number1, int number2) {
            System.out.println();

            
          }

          public static void main(String[] args) {
            System.out.println("smaller number is: " + calculateSmallerNumber(10, 15));
            System.out.println("smaller number is: " + calculateSmallerNumber(200, 95));
          }
        }
Solution:

        public class SmallerNumber {
          private static int calculateSmallerNumber(int number1, int number2) {
            System.out.println("number1=" + number1 + ", number2=" + number2);

            if(number1 < number2) {
              return number1;
            }
            else {
              return number2;
            }
          }

          public static void main(String[] args) {
            System.out.println("smaller number is: " + calculateSmallerNumber(10, 15));
            System.out.println("smaller number is: " + calculateSmallerNumber(200, 95));
          }
        }
        
1. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Implement **calculateLargestNumber**. Print **number1**, **number2** and **number3** in same line. Add logic in nested if else statements to check largest number.     
Question:

        public class LargestNumber {
          private static int calculateLargestNumber(int number1, int number2, int number3) {
            System.out.println();

            
          }

          public static void main(String[] args) {
            System.out.println("largest number is: " + calculateLargestNumber(10, 9, 100));
            System.out.println("largest number is: " + calculateLargestNumber(9, 100, 10));
            System.out.println("largest number is: " + calculateLargestNumber(100, 10, 9));
            System.out.println("largest number is: " + calculateLargestNumber(-1, -2, -3));
          }
        }
Solution:

        public class LargestNumber {
          private static int calculateLargestNumber(int number1, int number2, int number3) {
            System.out.println("number1=" + number1 + ", number2=" + number2 + ", number3=" + number3);

            if(number1 > number2) {
              if(number1 > number3){
                return number1;
              }
              else {
                return number3;
              }
            }
            else {
              if(number2 > number3){
                return number2;
              }
              else {
                return number3;
              }
            }
          }

          public static void main(String[] args) {
            System.out.println("largest number is: " + calculateLargestNumber(10, 9, 100));
            System.out.println("largest number is: " + calculateLargestNumber(9, 100, 10));
            System.out.println("largest number is: " + calculateLargestNumber(100, 10, 9));
            System.out.println("largest number is: " + calculateLargestNumber(-1, -2, -3));
          }
        }
        
1. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Implement **calculateLargestNumber**. Print **number1**, **number2** and **number3** in same line. Add logic in nested if else statements to check largest number.     
Question:

        public class LargestNumber {
          private static int calculateLargestNumber(int number1, int number2, int number3) {
            System.out.println();

            
          }

          private static int greaterNumber(int x, int y) {
            if(x > y){
              return x;
            }
            else {
              return y;
            }
          }

          public static void main(String[] args) {
            System.out.println("largest number is: " + calculateLargestNumber(10, 9, 100));
            System.out.println("largest number is: " + calculateLargestNumber(9, 100, 10));
            System.out.println("largest number is: " + calculateLargestNumber(100, 10, 9));
            System.out.println("largest number is: " + calculateLargestNumber(-1, -2, -3));
          }
        }
Solution:

        public class LargestNumber {
          private static int calculateLargestNumber(int number1, int number2, int number3) {
            System.out.println("number1=" + number1 + ", number2=" + number2 + ", number3=" + number3);

            if(number1 > number2) {
              return greaterNumber(number1, number3);
            }
            else {
              return greaterNumber(number2, number3);
            }
          }

          private static int greaterNumber(int x, int y) {
            if(x > y){
              return x;
            }
            else {
              return y;
            }
          }

          public static void main(String[] args) {
            System.out.println("largest number is: " + calculateLargestNumber(10, 9, 100));
            System.out.println("largest number is: " + calculateLargestNumber(9, 100, 10));
            System.out.println("largest number is: " + calculateLargestNumber(100, 10, 9));
            System.out.println("largest number is: " + calculateLargestNumber(-1, -2, -3));
          }
        }
        
1. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Implement **calculateLargestNumber**. Print **number1**, **number2** and **number3** in same line. Add logic in nested if else statements to check largest number.     
Question:

        public class LargestNumber {
          private static int calculateLargestNumber(int number1, int number2, int number3) {
            System.out.println();

            
          }

          private static int greaterNumber(int x, int y) {
            if(x > y){
              return x;
            }
            else {
              return y;
            }
          }

          public static void main(String[] args) {
            System.out.println("largest number is: " + calculateLargestNumber(10, 9, 100));
            System.out.println("largest number is: " + calculateLargestNumber(9, 100, 10));
            System.out.println("largest number is: " + calculateLargestNumber(100, 10, 9));
            System.out.println("largest number is: " + calculateLargestNumber(-1, -2, -3));
          }
        }
Solution:

        public class LargestNumber {
          private static int calculateLargestNumber(int number1, int number2, int number3) {
            System.out.println("number1=" + number1 + ", number2=" + number2 + ", number3=" + number3);

            int tempResult = greaterNumber(number1, number2);

            return greaterNumber(tempResult, number3);
          }

          private static int greaterNumber(int x, int y) {
            if(x > y){
              return x;
            }
            else {
              return y;
            }
          }

          public static void main(String[] args) {
            System.out.println("largest number is: " + calculateLargestNumber(10, 9, 100));
            System.out.println("largest number is: " + calculateLargestNumber(9, 100, 10));
            System.out.println("largest number is: " + calculateLargestNumber(100, 10, 9));
            System.out.println("largest number is: " + calculateLargestNumber(-1, -2, -3));
          }
        }        

1. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Implement **calculateLargestNumber**. Print **number1**, **number2** and **number3** in same line. Add logic in nested if else statements to check largest number.     
Question:

        public class LargestNumber {
          private static int calculateLargestNumber(int number1, int number2, int number3) {
            System.out.println();

            
          }

          private static int greaterNumber(int x, int y) {
            if(x > y){
              return x;
            }
            else {
              return y;
            }
          }

          public static void main(String[] args) {
            System.out.println("largest number is: " + calculateLargestNumber(10, 9, 100));
            System.out.println("largest number is: " + calculateLargestNumber(9, 100, 10));
            System.out.println("largest number is: " + calculateLargestNumber(100, 10, 9));
            System.out.println("largest number is: " + calculateLargestNumber(-1, -2, -3));
          }
        }
Solution:

        public class LargestNumber {
          private static int calculateLargestNumber(int number1, int number2, int number3) {
            System.out.println("number1=" + number1 + ", number2=" + number2 + ", number3=" + number3);

            return greaterNumber((number1, number2), number3);
          }

          private static int greaterNumber(int x, int y) {
            if(x > y){
              return x;
            }
            else {
              return y;
            }
          }

          public static void main(String[] args) {
            System.out.println("largest number is: " + calculateLargestNumber(10, 9, 100));
            System.out.println("largest number is: " + calculateLargestNumber(9, 100, 10));
            System.out.println("largest number is: " + calculateLargestNumber(100, 10, 9));
            System.out.println("largest number is: " + calculateLargestNumber(-1, -2, -3));
          }
        }
        
1. **Theory**:    `r text_spec("TODO", color = "red", bold = TRUE)`         
Ternary introduction.   

1. **Example**:    `r text_spec("TODO", color = "red", bold = TRUE)`        
How to use ternary operations.   
        
1. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Implement **calculateLargestNumber**. Use ternary operator to check greater number.     
Question:

        public class GreaterNumber {
          private static int calculateGreaterNumber(int number1, int number2) {
            System.out.println("number1=" + number1 + ", number2=" + number2);

            int result = 
            return result;
          }

          public static void main(String[] args) {
            System.out.println("greater number is: " + calculateGreaterNumber(10, 20));
            System.out.println("greater number is: " + calculateGreaterNumber(-2, 0));
            System.out.println("greater number is: " + calculateGreaterNumber(-5, -15));
            System.out.println("greater number is: " + calculateGreaterNumber(1, 200));
          }
        } 
Solution:

        public class GreaterNumber {
          private static int calculateGreaterNumber(int number1, int number2) {
            System.out.println("number1=" + number1 + ", number2=" + number2);

            int result = number1 > number2 ? number1 : number2;
            return result;
          }

          public static void main(String[] args) {
            System.out.println("greater number is: " + calculateGreaterNumber(10, 20));
            System.out.println("greater number is: " + calculateGreaterNumber(-2, 0));
            System.out.println("greater number is: " + calculateGreaterNumber(-5, -15));
            System.out.println("greater number is: " + calculateGreaterNumber(1, 200));
          }
        } 
        
1. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Implement **calculateLargestNumber**. Use ternary operator to check greater number.     
Question:

        public class GreaterNumber {
          private static int calculateGreaterNumber(int number1, int number2) {
            System.out.println("number1=" + number1 + ", number2=" + number2);

          }

          public static void main(String[] args) {
            System.out.println("greater number is: " + calculateGreaterNumber(10, 20));
            System.out.println("greater number is: " + calculateGreaterNumber(-2, 0));
            System.out.println("greater number is: " + calculateGreaterNumber(-5, -15));
            System.out.println("greater number is: " + calculateGreaterNumber(1, 200));
          }
        } 
Solution:

        public class GreaterNumber {
          private static int calculateGreaterNumber(int number1, int number2) {
            System.out.println("number1=" + number1 + ", number2=" + number2);

            return number1 > number2 ? number1 : number2;
          }

          public static void main(String[] args) {
            System.out.println("greater number is: " + calculateGreaterNumber(10, 20));
            System.out.println("greater number is: " + calculateGreaterNumber(-2, 0));
            System.out.println("greater number is: " + calculateGreaterNumber(-5, -15));
            System.out.println("greater number is: " + calculateGreaterNumber(1, 200));
          }
        }   
        
1. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Implement **calculateLargestNumber**. Print **number1**, **number2** and **number3** in same line. User ternary operations to check largest number.     
Question:

        public class LargestNumber {
          private static int calculateLargestNumber(int number1, int number2, int number3) {
            System.out.println();

            
          }

          public static void main(String[] args) {
            System.out.println("largest number is: " + calculateLargestNumber(10, 9, 100));
            System.out.println("largest number is: " + calculateLargestNumber(9, 100, 10));
            System.out.println("largest number is: " + calculateLargestNumber(100, 10, 9));
            System.out.println("largest number is: " + calculateLargestNumber(-1, -2, -3));
          }
        }
Solution:

        public class LargestNumber {
          private static int calculateLargestNumber(int number1, int number2, int number3) {
            System.out.println("number1=" + number1 + ", number2=" + number2 + ", number3=" + number3);

            int result = (number1 > number2) ? (number1 > number3 ? number1 : number3) : (number2 > number3 ? number2 : number3);
            return result;
          }

          public static void main(String[] args) {
            System.out.println("largest number is: " + calculateLargestNumber(10, 9, 100));
            System.out.println("largest number is: " + calculateLargestNumber(9, 100, 10));
            System.out.println("largest number is: " + calculateLargestNumber(100, 10, 9));
            System.out.println("largest number is: " + calculateLargestNumber(-1, -2, -3));
          }
        }
        
#### Loops {-}

16. **Theory**:    `r text_spec("TODO", color = "red", bold = TRUE)`         
for loop introduction.    

16. **Example**:    `r text_spec("TODO", color = "red", bold = TRUE)`        
How to use for loop.   

16. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Print **Java is going to be on my tips with practice.** 5 times in main method.   
Question:

        public class ForLoop {

          public static void main(String[] args) {
            System.out.println("");
            System.out.println("");
            System.out.println("");
            System.out.println("");
            System.out.println("");
          }
        }
Solution:

        public class ForLoop {

          public static void main(String[] args) {
            System.out.println("Java is going to be on my tips with practice.");
            System.out.println("Java is going to be on my tips with practice.");
            System.out.println("Java is going to be on my tips with practice.");
            System.out.println("Java is going to be on my tips with practice.");
            System.out.println("Java is going to be on my tips with practice.");
          }
        }
        
16. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Print **Java is going to be on my tips with practice.** 5 times using for loop in main method.   
Question:

        public class ForLoop {

          public static void main(String[] args) {
            for (){
              System.out.println("");
            }
          }
        }
Solution:

        public class ForLoop {

          public static void main(String[] args) {
            for (int i =0; i< 5; i++){
              System.out.println("Java is going to be on my tips with practice.");
            }
          }
        }
        
16. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Print **Practice makes programming perfect.** 10 times using for loop in main method.   
Question:

        public class ForLoop {

          public static void main(String[] args) {
            for (){
              System.out.println("");
            }
          }
        }
Solution:

        public class ForLoop {

          public static void main(String[] args) {
            for (int i=0; i< 10; i++){
              System.out.println("Practice makes programming perfect.");
            }
          }
        }
        
16. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Print loop number **j** inside for loop block in main method.   
Question:

        public class ForLoop {

          public static void main(String[] args) {
            for (int j=0; j< 10; j++){
              System.out.println();
            }
          }
        }
Solution:

        public class ForLoop {

          public static void main(String[] args) {
            for (int j=0; j< 10; j++){
              System.out.println(i);
            }
          }
        }
        
16. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Print message **"loop iteration="** and loop number **k** in same line, inside for loop block in main method.   
Question:

        public class ForLoop {

          public static void main(String[] args) {
            for (int k=0; k< 10; k++){
              System.out.println();
            }
          }
        }
Solution:

        public class ForLoop {

          public static void main(String[] args) {
            for (int k=0; k< 10; k++){
              System.out.println("loop iteration" + k);
            }
          }
        }
        
16. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Call **square** method 7 times with parameter 0 to 6 in main method.   
Question:

        public class ForLoop {
          static int square(int number){
            int squaredValue = number * number;
            System.out.println("Square of number " + number + " is = " + squaredValue);
            return squaredValue;
          }

          public static void main(String[] args) {
            
          }
        }
Solution:

        public class ForLoop {
          static int square(int number){
            int squaredValue = number * number;
            System.out.println("Square of number " + number + " is = " + squaredValue);
            return squaredValue;
          }

          public static void main(String[] args) {
            square(0);
            square(1);
            square(2);
            square(3);
            square(4);
            square(5);
            square(6);
          }
        }
        
16. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Call **square** method in for loop starting from 0 to max value 6 in main method. Pass for loop iteration value as argument of **square** method.   
Question:

        public class ForLoop {
          static int square(int number){
            int squaredValue = number * number;
            System.out.println("Square of number " + number + " is = " + squaredValue);
            return squaredValue;
          }

          public static void main(String[] args) {
            
          }
        }
Solution:

        public class ForLoop {
          static int square(int number){
            int squaredValue = number * number;
            System.out.println("Square of number " + number + " is = " + squaredValue);
            return squaredValue;
          }

          public static void main(String[] args) {
            for (int m=0; m< 7; m++){
             square(m);
            }
          }
        }  
        
16. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Call **square** method in for loop starting from 0 to max value 6 in main method. Add sqaure value to **total** variable such that it contains the value addition of all squared values.   
Question:

        public class ForLoop {
          static int square(int number){
            int squaredValue = number * number;
            System.out.println("Square of number " + number + " is = " + squaredValue);
            return squaredValue;
          }

          public static void main(String[] args) {
            int total = 0;

            for (int n=0; n< 7; n++){
              
            }

            System.out.println("total squared value = " + total);
          }
        }  
Solution:

        public class ForLoop {
          static int square(int number){
            int squaredValue = number * number;
            System.out.println("Square of number " + number + " is = " + squaredValue);
            return squaredValue;
          }

          public static void main(String[] args) {
            int total = 0;

            for (int n=0; n< 7; n++){
              total = total + square(n);
            }

            System.out.println("total squared value = " + total);
          }
        }  
   

### Module 04: OOPS {-}

#### Objects {-}

1. **Theory**:    `r text_spec("TODO", color = "red", bold = TRUE)`         
Object introduction   

1. **Example**:    `r text_spec("TODO", color = "red", bold = TRUE)`        
How to create object of a class   

1. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create object **emp** of **Employee** in main method.  
Print **emp**.   
Question:

        class Employee {

          public static void main(String[] args) {
            
            System.out.println();
          }
        }
Solution:

        class Employee {

          public static void main(String[] args) {
            Employee emp = new Employee();
            System.out.println(emp);
          }
        }

1. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create object **emp1** of **Employee** in main method.  
Print **emp1**.   
Create object **emp2** of **Employee** in main method.   
Print **emp2**.  
Question:

        class Employee {

          public static void main(String[] args) {
            
            System.out.println();
            
            
            System.out.println();
          }
        }
Solution:

        class Employee {

          public static void main(String[] args) {
            Employee emp1 = new Employee();
            System.out.println(emp1);
            
            Employee emp2 = new Employee();
            System.out.println(emp2);
          }
        }        

1. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create object **emp** of **Employee** in main method.  
Print **emp**.   
Create another object of **Employee** class and assign it to already created **emp**.     
Print **emp**.   
Question:

        class Employee {

          public static void main(String[] args) {
            
            System.out.println();
            
            
            System.out.println();
          }
        }
Solution:

        class Employee {

          public static void main(String[] args) {
            Employee emp = new Employee();
            System.out.println(emp);
            
            emp = new Employee();
            System.out.println(emp);
          }
        }        

1. **Theory**:    `r text_spec("TODO", color = "red", bold = TRUE)`         
Anonymous object introduction   

1. **Example**:    `r text_spec("TODO", color = "red", bold = TRUE)`        
How to create anonymous object of a class   

1. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create anonymous object of **Employee** in main method.   
Question:

        class Employee {

          public static void main(String[] args) {
            
          }
        }
Solution:

        class Employee {

          public static void main(String[] args) {
            new Employee();
          }
        }

1. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create anonymous object of **Employee** in print statement in main method and print its value.   
Question:

        class Employee {

          public static void main(String[] args) {
            System.out.println();
          }
        }
Solution:

        class Employee {

          public static void main(String[] args) {
            System.out.println(new Employee());
          }
        }        

#### Instance Data Members {-}

10. **Theory**:    `r text_spec("TODO", color = "red", bold = TRUE)`         
Importance of Instance data members.    

10. **Example**:    `r text_spec("TODO", color = "red", bold = TRUE)`        
How to create Instance data member and its usage in java file.    

10. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create object of **Student** class **student** in main method.   
Print **name** of **student** in main method.   
Question:
  
        class Student {
          String name;

          public static void main(String[] args) {
            
            System.out.println();
          }
        }
Question:
  
        class Student {
          String name;

          public static void main(String[] args) {
            Student student = new Student();
            System.out.println(student.name);
          }
        }        

10. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create object of **Student** class **student** in main method.   
Print **name** of **student** in main method.   
Assign value *Jack* to **name**.   
Print **name** of **student** in main method.   
Question:

        class Student {
          String name;

          public static void main(String[] args) {
            Student student = new Student();
            System.out.println(student.name);

            
            System.out.println();
          }
        }
Solution:

        class Student {
          String name;

          public static void main(String[] args) {
            Student student = new Student();
            System.out.println(student.name);

            student.name = "Jack";
            System.out.println(student.name);
          }
        }        

10. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Print **name** of **student1** in main method.   
Print **name** of **student2** in main method.   
Assign value *Jack* to **name** of **student1**.   
Assign value *Diana* to **name** of **student2**.   
Print **name** of **student1** and **student2** in main method.    
Question:

        class Student {
          String name;

          public static void main(String[] args) {
            Student student1 = new Student();
            Student student2 = new Student();

            System.out.println(student1.name);
            System.out.println(student2.name);

            
            

            System.out.println();
            System.out.println();
          }
        }
Question:

        class Student {
          String name;

          public static void main(String[] args) {
            Student student1 = new Student();
            Student student2 = new Student();

            System.out.println(student1.name);
            System.out.println(student2.name);

            student1.name = "Jack";
            student2.name = "Diana";

            System.out.println(student1.name);
            System.out.println(student2.name);
          }
        }

10. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Print **name** of **student1** in main method.   
Print **marks** of **student1** in main method.   
Print **name** of **student2** in main method.   
Print **marks** of **student2** in main method.    
Assign value *Jack* to **name** of **student1**.   
Assign value *Diana* to **name** of **student2**.   
Assign value *7* to **marks** of **student1**.   
Assign value *8* to **marks** of **student2**.    
Print **name** of **student1** in main method.   
Print **marks** of **student1** in main method.   
Print **name** of **student2** in main method.   
Print **marks** of **student2** in main method.   
Question:

        class Student {
          String name;
          int marks = 4;

          public static void main(String[] args) {
            Student student1 = new Student();
            Student student2 = new Student();

            System.out.println(student1.name);
            System.out.println(student1.marks);

            System.out.println(student2.name);
            System.out.println(student2.marks);

            
            

            
            

            System.out.println();
            System.out.println();

            System.out.println();
            System.out.println();
          }
        }
Solution:

        class Student {
          String name;
          int marks = 4;

          public static void main(String[] args) {
            Student student1 = new Student();
            Student student2 = new Student();

            System.out.println(student1.name);
            System.out.println(student1.marks);

            System.out.println(student2.name);
            System.out.println(student2.marks);

            student1.name = "Jack";
            student2.name = "Diana";

            student1.marks = 7;
            student2.marks = 8;

            System.out.println(student1.name);
            System.out.println(student1.marks);

            System.out.println(student2.name);
            System.out.println(student2.marks);
          }
        }        

10. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Print **name** of **student1** in main method.   
Print **marks** of **student1** in main method.   
Print **schoolName** of **student1** in main method.   
Print **name** of **student2** in main method.   
Print **marks** of **student2** in main method.  
Print **schoolName** of **student2** in main method.   
Assign value *Better Study School* to **schoolName**.   
Print value of **schoolName** in main method.   
Assign value *Jack* to **name** of **student1**.   
Assign value *Diana* to **name** of **student2**.   
Assign value *7* to **marks** of **student1**.   
Assign value *8* to **marks** of **student2**.    
Print **name** of **student1** in main method.   
Print **marks** of **student1** in main method.   
Print **schoolName** of **student1** in main method.   
Print **name** of **student2** in main method.   
Print **marks** of **student2** in main method.  
Print **schoolName** of **student2** in main method.   
Question:

        class Student {
          String name;
          int marks = 4;
          static String schoolName = "Good Study School";

          public static void main(String[] args) {
            Student student1 = new Student();
            Student student2 = new Student();

            System.out.println(student1.name);
            System.out.println(student1.marks);
            System.out.println(student1.schoolName);

            System.out.println(student2.name);
            System.out.println(student2.marks);
            System.out.println(student2.schoolName);

            
            System.out.println(schoolName);

            
            

            
            

            System.out.println();
            System.out.println();
            System.out.println();

            System.out.println();
            System.out.println();
            System.out.println();
          }
        }
Solution:

        class Student {
          String name;
          int marks = 4;
          static String schoolName = "Good Study School";

          public static void main(String[] args) {
            Student student1 = new Student();
            Student student2 = new Student();

            System.out.println(student1.name);
            System.out.println(student1.marks);
            System.out.println(student1.schoolName);

            System.out.println(student2.name);
            System.out.println(student2.marks);
            System.out.println(student2.schoolName);

            schoolName = "Better Study School";
            System.out.println(schoolName);

            student1.name = "Jack";
            student2.name = "Diana";

            student1.marks = 7;
            student2.marks = 8;

            System.out.println(student1.name);
            System.out.println(student1.marks);
            System.out.println(student1.schoolName);

            System.out.println(student2.name);
            System.out.println(student2.marks);
            System.out.println(student2.schoolName);
          }
        }        

10. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create anonymous object of **Person** in print statement and print value of **salary** on it, in main method.   
Question:

        class Person {
          int salary = 10000;
          
          public static void main(String[] args) {
            System.out.println(new Person().salary);
          }
        }
Solution:

        class Person {
          int salary = 10000;
          
          public static void main(String[] args) {
            System.out.println();
          }
        }        

#### Instance Methods {-}

18. **Theory**:    `r text_spec("TODO", color = "red", bold = TRUE)`         
Instance/Non-static method introduction   

18. **Example**:    `r text_spec("TODO", color = "red", bold = TRUE)`        
How to create Instance/Non-static method in a class   

18. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create instance method **displayValue()** which prints the value of **name**.   
Create object **person** of **Person** class  in main method.   
Call **displayValue()** on **person** in main method.    
Question:

        class Person {
          String name;
          
          void displayValue(){
            System.out.println();
          }

          public static void main(String[] args) {
            Person person = new Person();
            
          }
        }
Solution:

        class Person {
          String name;
          
          void displayValue(){
            System.out.println(name);
          }

          public static void main(String[] args) {
            Person person = new Person();
            person.displayValue();
          }
        }        

18. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create instance method **setValue(string newName)** which assigns the variable **newName** to **name**.   
Create object **person** of **Person** class  in main method.   
Call **setValue("Jack")** on **person** in main method.   
Call **displayValue()** on **person** in main method.     
Question:

        class Person {
          String name;
          
          void setValue(String newName){
            
          }

          void displayValue(){
            System.out.println(name);
          }

          public static void main(String[] args) {
            Person person = new Person();
            
            person.displayValue();
          }
        }
Solution:

        class Person {
          String name;
          
          void setValue(String newName){
            name = newName;
          }

          void displayValue(){
            System.out.println(name);
          }

          public static void main(String[] args) {
            Person person = new Person();
            person.setValue("Diana");
            person.displayValue();
          }
        }        

18. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create instance method **setValues(String newName, int newAge)** which assigns the variable **newName** to **name** and **newAge** to **age**.   
Create instance method **print()** which prints the value of **name** and **age**.   
Create object **person** of **Person** class  in main method.    
Call **setValues("Diana", 19)** on **person** in main method.    
Call **displayValues()** on **person** in main method.    
Question:

        class Person {
          String name;
          int age;

          void setValues(String newName, int newAge){
            
            
          }

          void displayValues(){
            System.out.println(name);
            System.out.println(age);
          }

          public static void main(String[] args) {
            Person person = new Person();
            
            
          }
        }
Solution:

        class Person {
          String name;
          int age;

          void setValues(String newName, int newAge){
            name = newName;
            age = newAge;
          }

          void displayValues(){
            System.out.println(name);
            System.out.println(age);
          }

          public static void main(String[] args) {
            Person person = new Person();
            person.setValues("Diana", 19);
            person.displayValues();
          }
        }        

18. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Call **person1**.**setValues("Jack", 21)** in main method.   
Call **person2**.**setValues("Diana", 19)** in main method.   
Call **person1**.**displayValues()** in main method.     
Call **person2**.**displayValues()** in main method.     
Question:

        class Person {
          String name;
          int age;

          void setValues(String newName, int newAge){
            name = newName;
            age = newAge;
          }

          void displayValues(){
            System.out.println(name);
            System.out.println(age);
          }

          public static void main(String[] args) {
            Person person1 = new Person();
            Person person2 = new Person();

            
            

            
            
          }
        }
Solution:

        class Person {
          String name;
          int age;

          void setValues(String newName, int newAge){
            name = newName;
            age = newAge;
          }

          void displayValues(){
            System.out.println(name);
            System.out.println(age);
          }

          public static void main(String[] args) {
            Person person1 = new Person();
            Person person2 = new Person();

            person1.setValues("Jack", 21);
            person2.setValues("Diana", 19);

            person1.displayValues();
            person2.displayValues();
          }
        }        

18. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Call **student**.**displayValues()** in main method.    
Call **student**.**modifyValues("Jack", 7)** in main method.    
Call **student**.**displayValues()** in main method.    
Call **student**.**modifyValues("Harry", 6)** in main method.   
Call **student**.**displayValues()** in main method.   
Call **student**.**modifyValues("Krish", 8)** in main method.   
Call **student**.**displayValues()** in main method.   
Question:

        class Student {
          String name = "Tom";
          int marks = 4;

          void modifyValues(String newName, int newMarks){
            name = newName;
            marks = newMarks;
          }

          void displayValues(){
            System.out.println(name + ", " + marks);
          }

          public static void main(String[] args) {
            Student student = new Student();
            
            student.displayValues();
            
            
            student.displayValues();
            
            
            student.displayValues();
            
            
            student.displayValues();
          }
        }
Question:

        class Student {
          String name = "Tom";
          int marks = 4;

          void modifyValues(String newName, int newMarks){
            name = newName;
            marks = newMarks;
          }

          void displayValues(){
            System.out.println(name + ", " + marks);
          }

          public static void main(String[] args) {
            Student student = new Student();
            
            student.displayValues();
            
            student.modifyValues("Jack", 7);
            student.displayValues();
            
            student.modifyValues("Harry", 6);
            student.displayValues();
            
            student.modifyValues("Krish", 8);
            student.displayValues();
          }
        }

18. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Call **student1**.**displayValues()** in main method.    
Call **student2**.**displayValues()** in main method.    
Call **student1**.**modifyValues("Jack" , 22, "Shawn")** in main method.    
Call **student2**.**modifyValues("Diana" , 17, "Hilton")** in main method.    
Call **student1**.**displayValues()** in main method.    
Call **student2**.**displayValues()** in main method.    
Question:

        class Student {
          String name;
          int marks = 4;
          static String schoolName = "Good Study School";

          void modifyValues(String newName, int newMarks, String schoolNewName){
            name = newName;
            marks = newMarks;
            schoolName = schoolNewName;
          }

          void displayValues(){
            System.out.println(name);
            System.out.println(marks);
            System.out.println(schoolName);
          }

          public static void main(String[] args) {
            Student student1 = new Student();
            Student student2 = new Student();

            student1.displayValues();
            student2.displayValues();

            student1.modifyValues();
            student2.modifyValues();

            
            
          }
        }
Solution:

        class Student {
          String name;
          int marks = 4;
          static String schoolName = "Good Study School";

          void modifyValues(String newName, int newMarks, String schoolNewName){
            name = newName;
            marks = newMarks;
            schoolName = schoolNewName;
          }

          void displayValues(){
            System.out.println(name);
            System.out.println(marks);
            System.out.println(schoolName);
          }

          public static void main(String[] args) {
            Student student1 = new Student();
            Student student2 = new Student();

            student1.displayValues();
            student2.displayValues();

            student1.modifyValues("Jack", 7, "Better Study School");
            student2.modifyValues("Diana", 8, "Best Study School");

            student1.displayValues();
            student2.displayValues();
          }
        }

18. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create instance method **setName(String newName)** which will assign **newName** to **name**.   
Create instance method **setSalary(int newSalary)** which will assign **newSalary** to **salary**.   
Create object **emp1** of **Employee** class in main method.   
Call **displayCompanyName()**.   
Call **emp1**.**setName("Maria")**.   
Call **emp1**.**setSalary(12000)**.   
Call **emp1**.**displayName()**.   
Call **emp1**.**displaySalary()**.   
Call **emp1**.**displayCompanyName()**.   
Create object **emp2** of **Employee** class in main method.   
Call **displayCompanyName()**.   
Call **emp2**.**setName("Harry")**.   
Call **emp2**.**displayName()**.   
Call **emp2**.**displaySalary()**.   
Call **emp2**.**displayCompanyName()**.   
Call **setCompanyName("ReadyFolks")**.   
Call **emp1**.**displayCompanyName()**.   
Call **emp2**.**displayCompanyName()**.   
Question:

        class Employee{
          static String companyName = "Folks";
          String name;
          int salary = 10000;

          static void displayCompanyName(){
            System.out.println(companyName);
          }

          void displayName(){
            System.out.println(name);
          }

          void displaySalary(){
            System.out.println(salary);
          }

          static void setCompanyName(String companyNewName) {
            companyName = companyNewName;
          }

          
          
          

          
          
          

          public static void main(String[] args) {
            
            displayCompanyName();
            emp1.setName("Maria");
            emp1.setSalary(12000);
            emp1.displayName();
            emp1.displaySalary();
            emp1.displayCompanyName();

            
            displayCompanyName();
            emp2.setName("Harry");
            emp2.displayName();
            emp2.displaySalary();
            emp2.displayCompanyName();

            setCompanyName("ReadyFolks");

            emp1.displayCompanyName();
            emp2.displayCompanyName();
          }
        }
Solution:

        class Employee{
          static String companyName = "Folks";
          String name;
          int salary = 10000;

          static void displayCompanyName(){
            System.out.println(companyName);
          }

          void displayName(){
            System.out.println(name);
          }

          void displaySalary(){
            System.out.println(salary);
          }

          static void setCompanyName(String companyNewName) {
            companyName = companyNewName;
          }

          void setName(String newName) {
            name = newName;
          }

          void setSalary(int newSalary) {
            salary = newSalary;
          }

          public static void main(String[] args) {
            Employee emp1 = new Employee();
            displayCompanyName();
            emp1.setName("Maria");
            emp1.setSalary(12000);
            emp1.displayName();
            emp1.displaySalary();
            emp1.displayCompanyName();

            Employee emp2 = new Employee();
            displayCompanyName();
            emp2.setName("Harry");
            emp2.displayName();
            emp2.displaySalary();
            emp2.displayCompanyName();

            setCompanyName("ReadyFolks");

            emp1.displayCompanyName();
            emp2.displayCompanyName();
          }
        }        

18. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create class **Employee**.   
Create instance data member **name**.   
Create instance data member **salary** with default value *10000*.   
Create instance method **displayName()** which will display value of **name**.   
Create instance method **displaySalary()** which will display value of **salary**.   
Create instance method **setName(String newName)** which will assign **newName** to **name**.   
Create instance method **setSalary(int newSalary)** which will assign **newSalary** to **salary**.   
Create anonymous object of **Employee** class and call **setName("Maria")** on it in main method.   
Create anonymous object of **Employee** class and call **displayName()** on it in main method.   
Question:

        class Employee{
          String name;
          
          void setName(String newName) {
            name = newName;
          }

          void displayName(){
            System.out.println(name);
          }

          public static void main(String[] args) {
            
            
          }
        }
Solution:

        class Employee{
          String name;
          
          void setName(String newName) {
            name = newName;
          }

          void displayName(){
            System.out.println(name);
          }

          public static void main(String[] args) {
            new Employee().setName("Maria");
            new Employee().displayName();
          }
        }        

18. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create class **Employee**.   
Create instance data member **firstName**.   
Create instance data member **lastName**.   
Create instance method **getFirstName()** which returns value of **firstName**.   
Create instance method **getLastName()** which returns value of **lastName**.   
Create instance method **displayFullName()** which prints full name by calling **getFirstName()** and **getLastName()** methods and appending them with space in between.   
Create object **emp** of **Employee** class in main method.   
Call **emp**.**displayFullName()**.   
Question:

        class Employee{
          String firstName;
          String lastName;

          String getFirstName() {
            return firstName;
          }

          String getLastName() {
            return lastName;
          }

          void displayFullName(){
            System.out.println();
          }

          public static void main(String[] args) {
            
            
          }
        }
Solution:

        class Employee{
          String firstName;
          String lastName;

          String getFirstName() {
            return firstName;
          }

          String getLastName() {
            return lastName;
          }

          void displayFullName(){
            System.out.println(getFirstName() + " " + getLastName());
          }

          public static void main(String[] args) {
            Employee emp = new Employee();
            emp.displayFullName();
          }
        }        

#### Method Overloading {-}

29. **Theory**:    `r text_spec("TODO", color = "red", bold = TRUE)`         
Method overloading introduction      

29. **Example**:    `r text_spec("TODO", color = "red", bold = TRUE)`        
How to do method overloading   

29. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create class **MethodOverloadingSample**.   
Create static method **getSquareArea(int number)** which returns area of square.   
Create static method **getRectangleArea(int length, int width)** which returns area of rectangle.   
Call **getSquareArea(5)** in main method.   
Call **getRectangleArea(5, 7)** in main method.   
Question:

        class MethodOverloadingSample{
          static int getSquareArea(int number){
            
          }

          static int getRectangleArea(int length, int width){
            
          }

          public static void main(String[] args) {
            int squareArea = getSquareArea(5);
            System.out.println(squareArea);
            
            int rectangleArea = getRectangleArea(5, 7);
            System.out.println(rectangleArea);
          }
        }
Solution:

        class MethodOverloadingSample{
          static int getSquareArea(int number){
            return number * number;
          }

          static int getRectangleArea(int length, int width){
            return length * width;
          }

          public static void main(String[] args) {
            int squareArea = getSquareArea(5);
            System.out.println(squareArea);
            
            int rectangleArea = getRectangleArea(5, 7);
            System.out.println(rectangleArea);
          }
        }        

29. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create class **MethodOverloadingSample**.   
Create static method **getArea(int number)** which returns area of square.   
Create static method **getArea(int length, int width)** which returns area of rectangle.   
Call **getArea(5)** in main method.   
Call **getArea(5, 7)** in main method.   
Question:

        class MethodOverloadingSample{
          static int getArea(int number){
            
          }

          
          
          

          public static void main(String[] args) {
            int squareArea = getArea(5);
            System.out.println(squareArea);
            
            int rectangleArea = getArea(5, 7);
            System.out.println(rectangleArea);
          }
        }
Solution:

        class MethodOverloadingSample{
          static int getArea(int number){
            return number * number;
          }

          static int getArea(int length, int width){
            return length * width;
          }

          public static void main(String[] args) {
            int squareArea = getArea(5);
            System.out.println(squareArea);
            
            int rectangleArea = getArea(5, 7);
            System.out.println(rectangleArea);
          }
        }        

29. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create class **MethodOverloadingSample**.   
Create static method **printInt(int number)** which prints the provided integer number.   
Create static method **printString(String message)** which prints the provided message.
Call **printInt(5)** in main method.   
Call **printString("so  many print methods")** in main method.  
Question:

        class MethodOverloadingSample{
          static void printChar(char ch){
            System.out.println(ch);
          }

          static void printNumber(int number){
            System.out.println(number);
          }
          
          
          
          
          
          static void printString(String message){
            System.out.println(message);
          }

          public static void main(String[] args) {
            printInt(5);
            printString("so  many print methods");
            printFloat(10.9f);
            printChar('a');
          }
        }
Solution:

        class MethodOverloadingSample{
          static void printChar(char ch){
            System.out.println(ch);
          }

          static void printNumber(int number){
            System.out.println(number);
          }
          
          static void printFloat(float number){
            System.out.println(number);
          }
          
          static void printString(String message){
            System.out.println(message);
          }

          public static void main(String[] args) {
            printInt(5);
            printString("so  many print methods");
            printFloat(10.9f);
            printChar('a');
          }
        }        

29. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create class **MethodOverloadingSample**.   
Create static method **print(int number)** which prints the provided integer number.   
Create static method **print(String message)** which prints the provided message.
Call **print(5)** in main method.   
Call **print("so  many print methods")** in main method.   
Question:

        class MethodOverloadingSample{
          static void print(int number){
            System.out.println(number);
          }
          
          
          
          

          public static void main(String[] args) {
            
            print("method overloading is fun. no need to remember so many method names");
          }
        }
Solution:

        class MethodOverloadingSample{
          static void print(int number){
            System.out.println(number);
          }
          
          static void print(String message){
            System.out.println(message);
          }

          public static void main(String[] args) {
            print(5);
            print("method overloading is fun. no need to remember so many method names");
          }
        }

29. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create class **MethodOverloadingSample**.   
Create static method **print(char ch)** which prints the provided integer number.   
Create static method **print(int number)** which prints the provided integer number.   
Create static method **print(float number)** which prints the provided integer number.   
Create static method **print(String message)** which prints the provided message.   
Call **print(5)** in main method.   
Call **print("method overloading is fun. no need to remember so many method names")** in main method.   
Call **print(20.03f)** in main method.  
Call **print('a')** in main method.    
Question:

        class MethodOverloadingSample{
          static void print(char ch){
            System.out.println(ch);
          }

          static void print(int number){
            System.out.println(number);
          }
          
          static void print(float number){
            System.out.println(number);
          }
          
          static void print(String message){
            System.out.println(message);
          }

          public static void main(String[] args) {
            print(5);
            print("method overloading is fun. no need to remember so many method names");
            print(10.9f);
            print('a');
          }
        }
Solution:

        class MethodOverloadingSample{
          static void print(char ch){
            System.out.println(ch);
          }

          static void print(int number){
          
          }
          
          
          
          
          
          static void print(String message){
            System.out.println(message);
          }

          public static void main(String[] args) {
            print(5);
            print("method overloading is fun. no need to remember so many method names");
            print(10.9f);
            print('a');
          }
        }        

29. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create class **MethodOverloadingSample**.   
Create static method **print(int x, float y)** which prints the provided integer number and float number.   
Create static method **print(float x, int y)** which prints the provided float number and integer number.   
Call **print(10, 10.9f)** in main method.   
Call **print(10.9f, 10)** in main method.       
Call **print(10, 10)** in main method.    
Question:

        class MethodOverloadingSample{
          static void print(int x, float y){
            System.out.println(x);
            System.out.println(y);
          }

          
          
          
          

          public static void main(String[] args) {
            print(10, 10.9f);
            print(10.9f, 10);
            //print(10, 10);
          }
        }
Solution:

        class MethodOverloadingSample{
          static void print(int x, float y){
            System.out.println(x);
            System.out.println(y);
          }

          static void print(float x, int y){
            System.out.println(x);
            System.out.println(y);
          }

          public static void main(String[] args) {
            print(10, 10.9f);
            print(10.9f, 10);
            //print(10, 10);
          }
        }        

#### Constructors {-}

37. **Theory**:    `r text_spec("TODO", color = "red", bold = TRUE)`         
Constructors introduction.         

37. **Example**:    `r text_spec("TODO", color = "red", bold = TRUE)`        
How to use constructors.   

37. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create class **Employee**.   
Create empty constructor **Employee()**.   
Create static method **greeting()** which prints *"Welcome partners..!!"*.   
Call **greeting()** in main method.     
Question:

        class Employee {

          Employee(){
            System.out.println("");
          }
          
          static void greetings(){
            System.out.println("Welcome partner..!!");
          }

          public static void main(String[] args) {
            greetings();
          }
        }
Solution:

        class Employee {

          Employee(){
            System.out.println("New employee joined");
          }
          
          static void greetings(){
            System.out.println("Welcome partner..!!");
          }

          public static void main(String[] args) {
            greetings();
          }
        }        

37. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create class **Employee**.   
Create constructor **Employee()** which prints *"New employee joined"*.   
Create instance method **greeting()** which prints *"Welcome partner..!!"*.   
Create object **emp** of **Employee** class in main method.   
Call **emp**.**greeting()** in main method.     
Question:

        class Employee {

          
          
          
          
          void greetings(){
            System.out.println("Welcome partner..!!");
          }

          public static void main(String[] args) {
            Employee emp = new Employee();
            emp.greetings();
          }
        }
Solution:

        class Employee {

          Employee(){
            System.out.println("New employee joined");
          }
          
          void greetings(){
            System.out.println("Welcome partner..!!");
          }

          public static void main(String[] args) {
            Employee emp = new Employee();
            emp.greetings();
          }
        }        

37. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create class **Employee**.   
Create constructor **Employee()** which prints *"New employee joined"*.   
Create instance method **greeting()** which prints *"Welcome partner..!!"*.   
Create anonymous object of **Employee** class and call **greeting()** in main method.   
Question:

        class Employee {

          Employee(){
            System.out.println("");
          }
          
          void greetings(){
            System.out.println("");
          }

          public static void main(String[] args) {
            
          }
        }
Solution:

        class Employee {

          Employee(){
            System.out.println("New employee joined");
          }
          
          void greetings(){
            System.out.println("Welcome partner..!!");
          }

          public static void main(String[] args) {
            new Employee().greetings();
          }
        }        

37. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create class **Employee**.  
Create instance data member **name**.   
Create constructor **Employee()** which prints *"New employee joined"*.   
Create constructor **Employee(String empName)** which prints *"New employee "+empName+" joined"*.   
Create instance method **greeting()** which prints *"Welcome "+name+"..!!"*.   
Create object **emp1** of **Employee** class in main method.   
Call **emp1**.**greeting()** in main method.   
Create object **emp2** of **Employee** class with **Employee("Shane")** in main method.   
Call **emp2**.**greeting()** in main method.   
Question:

        class Employee {
          String name;

          Employee(){
            System.out.println("New employee joined");
          }
          
          Employee(String empName){
            name=empName;
            System.out.println("");
          }
          
          void greetings(){
            System.out.println("Welcome " + name + "..!!");
          }

          public static void main(String[] args) {
            
            emp1.greetings();
            
            
            emp2.greetings();
          }
        }
Question:

        class Employee {
          String name;

          Employee(){
            System.out.println("New employee joined");
          }
          
          Employee(String empName){
            name=empName;
            System.out.println("New employee "+empName+" joined");
          }
          
          void greetings(){
            System.out.println("Welcome " + name + "..!!");
          }

          public static void main(String[] args) {
            Employee emp1 = new Employee();
            emp1.greetings();
            
            Employee emp2 = new Employee("Shane");
            emp2.greetings();
          }
        }        

37. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create object **emp** of **Employee** class with **Employee("Shane")** in main method.   
Call **emp**.**greeting()** in main method.     
Question:
  
        class Employee {
          String name;

          Employee(String empName){
            name=empName;
            System.out.println("New employee "+empName+" joined");
          }

          void greetings(){
            System.out.println("Welcome " + name + "..!!");
          }

          public static void main(String[] args) {
            
            
          }
        }
Solution:

        class Employee {
          String name;

          Employee(String empName){
            name=empName;
            System.out.println("New employee "+empName+" joined");
          }

          void greetings(){
            System.out.println("Welcome " + name + "..!!");
          }

          public static void main(String[] args) {
            Employee emp = new Employee("Shane");
            emp.greetings();
          }
        }
        
37. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`   
Create static method with same name as class.   
Call this method in main method.   
Question:

        class Employee {
          Employee(){
            System.out.println("New employee joined with initial salary: 10,000/-");    
          }

          Employee(int yearsOfExperience){
            int salary = yearsOfExperience * 10000;
            System.out.println("New employee joined with salary: "+salary+"/-");
          }

          
          
          

          public static void main(String[] args) {
            Employee emp1 = new Employee();
            
            new Employee();
            
            Employee emp2 = new Employee(2);
            Employee emp3 = new Employee();
            Employee emp4 = new Employee(3);
            Employee emp5 = new Employee();
          }
        }
Solution:

        class Employee {
          Employee(){
            System.out.println("New employee joined with initial salary: 10,000/-");    
          }

          Employee(int yearsOfExperience){
            int salary = yearsOfExperience * 10000;
            System.out.println("New employee joined with salary: "+salary+"/-");
          }

          static void Employee(){
            System.out.println("method with same class name");
          }

          public static void main(String[] args) {
            Employee emp1 = new Employee();
            Employee();
            new Employee();
            
            Employee emp2 = new Employee(2);
            Employee emp3 = new Employee();
            Employee emp4 = new Employee(3);
            Employee emp5 = new Employee();
          }
        }
        
37. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`   
Create instance method **commonTasksForEveryObject()**.   
Call **commonTasksForEveryObject()** in every constructor.   
Question:

        class Employee {
          Employee(){
            commonTasksForEveryObject();
            System.out.println("New employee joined with initial salary: 10,000/-");    
          }

          Employee(int yearsOfExperience){
            commonTasksForEveryObject();
            int salary = yearsOfExperience * 10000;
            System.out.println("New employee joined with salary: "+salary+"/-");
          }

          
          
          

          public static void main(String[] args) {
            Employee emp1 = new Employee();
            
            Employee emp2 = new Employee(2);
          }
        }
Solution:

        class Employee {
          Employee(){
            commonTasksForEveryObject();
            System.out.println("New employee joined with initial salary: 10,000/-");    
          }

          Employee(int yearsOfExperience){
            commonTasksForEveryObject();
            int salary = yearsOfExperience * 10000;
            System.out.println("New employee joined with salary: "+salary+"/-");
          }

          void commonTasksForEveryObject(){
            System.out.println("common tasks for every object");
          }

          public static void main(String[] args) {
            Employee emp1 = new Employee();
            
            Employee emp2 = new Employee(2);
          }
        }
        
37. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`   
Create instance method **commonTasksForEveryObject()**.   
Call **commonTasksForEveryObject()** in every constructor as first line, if not present.   
Question:

        class Employee {
          Employee(){
            commonTasksForEveryObject();
            System.out.println("New employee joined with initial salary: 10,000/-");    
          }

          Employee(int yearsOfExperience){
            
            int salary = yearsOfExperience * 10000;
            System.out.println("New employee joined with salary: "+salary+"/-");
          }

          
          
          

          public static void main(String[] args) {
            Employee emp1 = new Employee();
            
            Employee emp2 = new Employee(2);
          }
        }
Solution:

        class Employee {
          Employee(){
            commonTasksForEveryObject();
            System.out.println("New employee joined with initial salary: 10,000/-");    
          }

          Employee(int yearsOfExperience){
            commonTasksForEveryObject();
            int salary = yearsOfExperience * 10000;
            System.out.println("New employee joined with salary: "+salary+"/-");
          }

          void commonTasksForEveryObject(){
            System.out.println("common tasks for every object");
          }

          public static void main(String[] args) {
            Employee emp1 = new Employee();
            emp1.commonTasksForEveryObject();
            
            Employee emp2 = new Employee(2);
          }
        }

37. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`   
Create instance method **Employee()**.   
Call **Employee()** in every constructor as first line, if not present.   
Question:

        class Employee {
          Employee(){
            Employee();
            System.out.println("New employee joined with initial salary: 10,000/-");    
          }

          Employee(int yearsOfExperience){
            Employee();
            int salary = yearsOfExperience * 10000;
            System.out.println("New employee joined with salary: "+salary+"/-");
          }

          
          
          

          public static void main(String[] args) {
            Employee emp1 = new Employee();
            emp1.Employee();
            
            Employee emp2 = new Employee(2);
          }
        }
Solution:

        class Employee {
          Employee(){
            Employee();
            System.out.println("New employee joined with initial salary: 10,000/-");    
          }

          Employee(int yearsOfExperience){
            Employee();
            int salary = yearsOfExperience * 10000;
            System.out.println("New employee joined with salary: "+salary+"/-");
          }

          void Employee(){
            System.out.println("common tasks for every object");
          }

          public static void main(String[] args) {
            Employee emp1 = new Employee();
            emp1.Employee();
            
            Employee emp2 = new Employee(2);
          }
        }
        
#### Initialize Block {-}   

48. **Theory**:    `r text_spec("TODO", color = "red", bold = TRUE)`         
Importance of initialize block.    

48. **Example**:    `r text_spec("TODO", color = "red", bold = TRUE)`        
How to create initialize block in java file.

48. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create initialize block in java file which prints "In initialize block" message. Try execute this file.   
Question:

        class InitializeBlockExample {
          
          
          public static void main(String[] args){
            InitializeBlockExample obj = new InitializeBlockExample();
          }
        } 
Solution:

        class InitializeBlockExample {
          {
            System.out.println("In initialize block");
          }
          
          public static void main(String[] args){
            InitializeBlockExample obj = new InitializeBlockExample();
          }
        }  
        
48. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create first initialize block in java file which prints "In first initialize block" message.    
Create first initialize block in java file which prints "In second initialize block" message. Try execute this file.   
Question:

        class InitializeBlockExample {
          {
            
          }
          
          {
            
          }
          
          public static void main(String[] args){
            new InitializeBlockExample();
          }
        }  
Solution:

        class InitializeBlockExample {
          {
            System.out.println("In first initialize block");
          }
          
          {
            System.out.println("In second initialize block");
          }
          
          public static void main(String[] args){
            new InitializeBlockExample();
          }
        } 
        
48. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`       
Create anonymous object with constructor **InitializeBlockExample()** in main method.   
Create anonymous object with constructor **InitializeBlockExample("coding is iterative process")** in main method.   
Question:

        class InitializeBlockExample {
          {
            System.out.println("In first initialize block");
          }
          
          InitializeBlockExample(){
            System.out.println("default constructor called");
          }
          
          InitializeBlockExample(String message){
            System.out.println("constructor called with message: " + message);
          }
          
          {
            System.out.println("In second initialize block");
          }
          
          public static void main(String[] args){
            
            
          }
        }  
Solution:

        class InitializeBlockExample {
          {
            System.out.println("In first initialize block");
          }
          
          InitializeBlockExample(){
            System.out.println("default constructor called");
          }
          
          InitializeBlockExample(String message){
            System.out.println("constructor called with message: " + message);
          }
          
          {
            System.out.println("In second initialize block");
          }
          
          public static void main(String[] args){
            new InitializeBlockExample();
            new InitializeBlockExample("coding is iterative process");
          }
        }   
        
48. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`   
Calculate number of objects created.   
Create static data member **objectsCount** of type int.   
Increment **objectsCount** by 1 in initialize block.   
Print *"No. of objects created: " + objectsCount* in last line of main method.   
Question:

        class ObjectCounter {
          
          
          {
            
          }
          
          ObjectCounter(){
            System.out.println("default constructor called");
          }
          
          ObjectCounter(String message){
            System.out.println("constructor called with message: " + message);
          }
          
          ObjectCounter(int number){
            System.out.println("constructor called with number: " + number);
          }
          
          public static void main(String[] args){
            new ObjectCounter();
            new ObjectCounter(10);
            new ObjectCounter();
            new ObjectCounter("coding is iterative process");
            new ObjectCounter("hello");
            new ObjectCounter(100);
          }
        }  
Solution:

        class ObjectCounter {
          static int objectsCount = 0;
          
          {
            objectsCount++;
          }
          
          ObjectCounter(){
            System.out.println("default constructor called");
          }
          
          ObjectCounter(String message){
            System.out.println("constructor called with message: " + message);
          }
          
          ObjectCounter(int number){
            System.out.println("constructor called with number: " + number);
          }
          
          public static void main(String[] args){
            new ObjectCounter();
            new ObjectCounter(10);
            new ObjectCounter();
            new ObjectCounter("coding is iterative process");
            new ObjectCounter("hello");
            new ObjectCounter(100);
            
            System.out.printf("No. of objects created: " + objectsCount);
          }
        }   
        
#### this keyword  {-}  

54. **Theory**:    `r text_spec("TODO", color = "red", bold = TRUE)`         
Importance of this keyword as constructor in constructor chaining.     

54. **Example**:    `r text_spec("TODO", color = "red", bold = TRUE)`        
How to use this keyword as constructor in constructor chaining in java file.   
        
54. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`   
Constructor chaining.
Add *this()* as first statement in every constructor except **ConstructorChaining()**.   
Question:

        class ConstructorChaining {
          
          ConstructorChaining(){
            System.out.println("default constructor called");
          }
          
          ConstructorChaining(String message){
            
            System.out.println("constructor called with message: " + message);
          }
          
          ConstructorChaining(int number){
            
            System.out.println("constructor called with number: " + number);
          }
          
          public static void main(String[] args){
            new ConstructorChaining();
            new ConstructorChaining(10);
            new ConstructorChaining("coding is iterative process");
          }
        }  
Solution:

        class ConstructorChaining {
          
          ConstructorChaining(){
            System.out.println("default constructor called");
          }
          
          ConstructorChaining(String message){
            this();
            System.out.println("constructor called with message: " + message);
          }
          
          ConstructorChaining(int number){
            this();
            System.out.println("constructor called with number: " + number);
          }
          
          public static void main(String[] args){
            new ConstructorChaining();
            new ConstructorChaining(10);
            new ConstructorChaining("coding is iterative process");
          }
        }    
        
54. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`   
Constructor chaining.
Add *this(10)* as first statement in **ConstructorChaining()**.   
Add *this()* as first statement in **ConstructorChaining(String message)**.   
Question:

        class ConstructorChaining {
          
          ConstructorChaining(){
            System.out.println("default constructor called");
          }
          
          ConstructorChaining(String message){
            
            System.out.println("constructor called with message: " + message);
          }
          
          ConstructorChaining(int number){
            
            System.out.println("constructor called with number: " + number);
          }
          
          public static void main(String[] args){
            new ConstructorChaining();
            new ConstructorChaining(10);
            new ConstructorChaining("coding is iterative process");
          }
        }  
Solution:

        class ConstructorChaining {
          
          ConstructorChaining(){
            this(10);
            System.out.println("default constructor called");
          }
          
          ConstructorChaining(String message){
            this();
            System.out.println("constructor called with message: " + message);
          }
          
          ConstructorChaining(int number){
            System.out.println("constructor called with number: " + number);
          }
          
          public static void main(String[] args){
            new ConstructorChaining();
            new ConstructorChaining(10);
            new ConstructorChaining("coding is iterative process");
          }
        }    

54. **Theory**:    `r text_spec("TODO", color = "red", bold = TRUE)`         
Importance of this keyword as a reference to current object.   

54. **Example**:    `r text_spec("TODO", color = "red", bold = TRUE)`        
How to use this keyword as a reference to current object in java file.   

54. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`   
Print *this* as first statement in **takeCharge()**.   
Print *this* as first statement in **moveCharge()**.     
Call **player4**.**moveCharge()** as last statement in **takeCharge()**.   
Question:

        class Player {
          
          void takeCharge() {
            

            Player player2 = new Player();
            System.out.println(player2);

            System.out.println(this);

            Player player3 = new Player();
            System.out.println(player3);

            player3 .moveCharge();

            Player player4 = new Player();
            System.out.println(player4);

            System.out.println(this);
            
            
          }

          void moveCharge() {
            
          }

          public static void main(String[] args) {
            Player player1 = new Player();
            System.out.println(player1);

            player1.takeCharge();
          }
        } 
Solution:

        class Player {
          
          void takeCharge() {
            System.out.println(this);

            Player player2 = new Player();
            System.out.println(player2);

            System.out.println(this);

            Player player3 = new Player();
            System.out.println(player3);

            player3.moveCharge();

            Player player4 = new Player();
            System.out.println(player4);

            System.out.println(this);
            
            player4.moveCharge();
          }

          void moveCharge() {
            System.out.println(this);
          }

          public static void main(String[] args) {
            Player player1 = new Player();
            System.out.println(player1);

            player1.takeCharge();
          }
        } 
        
54. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`   
Assign value of local variable **ranking** to data member **ranking** in  **modifyValue(int ranking)** with help of **this** keyword.   
Question:

        class Player {
          int ranking = 10;

          void modifyValue(int ranking) {
            System.out.println("Before Change:");
            System.out.println("argument:" + ranking);
            System.out.println("data member:" + this.ranking);

            

            System.out.println("After Change:");
            System.out.println("argument:" + ranking);
            System.out.println("data member:" + this.ranking);
          }

          public static void main(String[] args) {
            Player player = new Player();
            System.out.println(player.ranking);
            player.modifyValue(7);
          }
        }
Solution:

        class Player {
          int ranking = 10;

          void modifyValue(int ranking) {
            System.out.println("Before Change:");
            System.out.println("argument:" + ranking);
            System.out.println("data member:" + this.ranking);

            this.ranking =ranking;

            System.out.println("After Change:");
            System.out.println("argument:" + ranking);
            System.out.println("data member:" + this.ranking);
          }

          public static void main(String[] args) {
            Player player = new Player();
            System.out.println(player.ranking);
            player.modifyValue(7);
          }
        }
        
#### Nested Classes  {-}          

62. **Theory**:    `r text_spec("TODO", color = "red", bold = TRUE)`         
Importance of  Nested Class.      

62. **Example**:    `r text_spec("TODO", color = "red", bold = TRUE)`        
How to create Nested Classes.   

62. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`   
Assign value of local variable **ranking** to data member **ranking** in  **modifyValue(int ranking)** with help of **this** keyword.   
Question:

        public class World {
          public static void main(String[] args) {
            
          }

          static class Human{
            
            
            
          }
        }
Solution:

        public class World {
          public static void main(String[] args) {
            Human h = new Human();
          }

          static class Human{
            String name;
            int age;
            String gender;
          }
        }
        
#### Association  {-}    

65. **Theory**:    `r text_spec("TODO", color = "red", bold = TRUE)`         
Importance of association.   

65. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`   
Create data member **rearLeftWheel** of type **Wheel** class in **Car** class with same values as front wheels.   
Create data member **rearRightWheel** of type **Wheel** class in **Car** class with same values as front wheels.   
Create data member **seatTwo** of type **Seat** class in **Car** class with same values of **seatOne**.   
Print details of **rearLeftWheel** in main method.
Print details of **rearRightWheel** in main method.   
Print details of **seatTwo** in main method.   
Question:

        public class AssociationExample {
          
          static class Car {
            String color;
            String companyName;
            String model;

            Wheel frontLeftWheel = new Wheel(4, "Alloy");
            Wheel frontRightWheel = new Wheel(4, "Alloy");
            
            

            Seat seatOne = new Seat(5, "Brown", "Leather-Premium", 5000);
            

            public Car(String color, String companyName, String model) {
              this.color = color;
              this.companyName = companyName;
              this.model = model;
            }
          }

          static class Wheel{
            int size;
            String type;

            Wheel(int size, String type){
              this.size = size;
              this.type = type;
            }
          }

          static class Seat{
            int size;
            String color;
            String type;
            int price;

            Seat(int size, String color, String type, int price){
              this.size = size;
              this.color = color;
              this.type = type;
              this.price = price;
            }
          }

          public static void main(String[] args) {
            Car car = new Car("White", "Ford", "Brazia");
            System.out.println("Car details: " + car.color + ", " + car.companyName + ", " + car.model);

            System.out.println("Front left wheel details: " + car.frontLeftWheel.size + ", " + car.frontLeftWheel.type);

            System.out.println("Front right wheel details: " + car.frontRightWheel.size + ", " + car.frontRightWheel.type);

            

            

            System.out.println("Seat one details: " + car.seatOne.color + ", " + car.seatOne.price + ", " + car.seatOne.size + ", " + car.seatOne.type);

            
          }
        }
Solution:

        public class AssociationExample {
          
          static class Car {
            String color;
            String companyName;
            String model;

            Wheel frontLeftWheel = new Wheel(4, "Alloy");
            Wheel frontRightWheel = new Wheel(4, "Alloy");
            Wheel rearLeftWheel = new Wheel(4, "Alloy");
            Wheel rearRightWheel = new Wheel(4, "Alloy");

            Seat seatOne = new Seat(5, "Brown", "Leather-Premium", 5000);
            Seat seatTwo = new Seat(5, "Brown", "Leather-Premium", 5000);

            public Car(String color, String companyName, String model) {
              this.color = color;
              this.companyName = companyName;
              this.model = model;
            }
          }

          static class Wheel{
            int size;
            String type;

            Wheel(int size, String type){
              this.size = size;
              this.type = type;
            }
          }

          static class Seat{
            int size;
            String color;
            String type;
            int price;

            Seat(int size, String color, String type, int price){
              this.size = size;
              this.color = color;
              this.type = type;
              this.price = price;
            }
          }

          public static void main(String[] args) {
            Car car = new Car("White", "Ford", "Brazia");
            System.out.println("Car details: " + car.color + ", " + car.companyName + ", " + car.model);

            System.out.println("Front left wheel details: " + car.frontLeftWheel.size + ", " + car.frontLeftWheel.type);

            System.out.println("Front right wheel details: " + car.frontRightWheel.size + ", " + car.frontRightWheel.type);

            System.out.println("Rear left wheel details: " + car.rearLeftWheel.size + ", " + car.rearLeftWheel.type);

            System.out.println("Rear right wheel details: " + car.rearRightWheel.size + ", " + car.rearRightWheel.type);

            System.out.println("Seat one details: " + car.seatOne.color + ", " + car.seatOne.price + ", " + car.seatOne.size + ", " + car.seatOne.type);

            System.out.println("Seat two details: " + car.seatTwo.color + ", " + car.seatTwo.price + ", " + car.seatTwo.size + ", " + car.seatTwo.type);
          }
        }
        
65. **Exercise**:    `r text_spec("TODO", color = "red", bold = TRUE)`   
Create data member **spouse** of type **Woman** class in **Man** class.   
Create data member **spouse** of type **Man** class in **Woman** class.   
Implement method **weddingCeremony**. Assign object **woman** to **spouse** data member of **man** object. Assign object **man** to **spouse** data member of **woman** object.   
Print details of **woman** in main method similar to **man** object.   
Question:

        public class Wedding {

          static class Man{
            String name;
            int age;
            

            Man(String name, int age){
              this.name = name;
              this.age = age;
            }
          }

          static class Woman{
            String name;
            int age;
            

            Woman(String name, int age){
              this.name = name;
              this.age = age;
            }
          }

          static void weddingCeremony(Man man, Woman woman){
            man.spouse = woman;
            woman.spouse = man;
          }

          public static void main(String[] args) {
            Man man = new Man("Harry", 29);
            Woman woman = new Woman("Diana", 31);

            weddingCeremony(man, woman);

            System.out.println("Man details=> name=" + man.name + ", age=" + man.age + ", wife name=" + man.spouse.name);
            
          }
        }
Solution:

        public class Wedding {

          static class Man{
            String name;
            int age;
            Woman spouse;

            Man(String name, int age){
              this.name = name;
              this.age = age;
            }
          }

          static class Woman{
            String name;
            int age;
            Man spouse;

            Woman(String name, int age){
              this.name = name;
              this.age = age;
            }
          }

          static void weddingCeremony(Man man, Woman woman){
            man.spouse = woman;
            woman.spouse = man;
          }

          public static void main(String[] args) {
            Man man = new Man("Harry", 29);
            Woman woman = new Woman("Diana", 31);

            weddingCeremony(man, woman);

            System.out.println("Man details=> name=" + man.name + ", age=" + man.age + ", wife name=" + man.spouse.name);
            System.out.println("Woman details=> name=" + woman.name + ", age=" + woman.age + ", husband name=" + woman.spouse.name);
          }
        }
     




















