@startmindmap
'https://plantuml.com/mindmap-diagram

caption figure 1
title Strategy Planning

* Strategies

** Reference

*** Syntax
**** Level 1 to Level 10

*** Core
**** Level 1 to Level 10

*** Multi-threading
**** Level 1 to Level 10

*** Collections
**** Level 1 to Level 10


** Codogenic

*** Core Java
**** JShell Module 1 (Module 1)
**** JShell Module 2 (Module 2)
**** Class, Main and static methods (Module 2)
**** Control flow statements (Module 3)
**** OOPS (Module 4)
**** Exception Handling (Module 5)
**** File Handling (Module 6)


*** Collections

*** Generics

*** Design Patterns

*** Mutithreading

*** Serialization Deserialization


center footer My super footer

legend right
  Reference level contains approx 20 to 30 problems
endlegend
@endmindmap
